sonar.projectKey=sga-app
sonar.projectName=SGA - Sistema de Gestao de Armaria
sonar.sources=src,server.ts,serverDb.ts,backend_python
sonar.exclusions=**/node_modules/**,**/dist/**,db.json,**/*.csv
sonar.sourceEncoding=UTF-8
