# Generated by Django 5.2.17 on 2026-08-12 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('calibre', models.CharField(blank=True, max_length=50)),
                ('comprimento_cano', models.CharField(blank=True, max_length=50)),
                ('quantidade_carregadores', models.IntegerField(blank=True, null=True)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('nivel', models.CharField(blank=True, max_length=50)),
                ('tamanho', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=100)),
                ('numero_empenho', models.CharField(blank=True, max_length=100)),
                ('numero_tombo', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('qtd_total', models.IntegerField(default=0)),
                ('qtd_disp', models.IntegerField(default=0)),
                ('qtd_min', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('dt_aq', models.DateField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dt_val', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='cadastros.fornecedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patrimonio', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('tamanho', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('qtd_total', models.IntegerField(default=0)),
                ('qtd_disp', models.IntegerField(default=0)),
                ('qtd_min', models.IntegerField(default=0)),
                ('dt_aq', models.DateField(blank=True, null=True)),
                ('dt_val', models.DateField(blank=True, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponível'), ('Em Uso', 'Em Uso'), ('Em Reparo', 'Em Reparo'), ('Recolhida', 'Recolhida'), ('Apreendida', 'Apreendida'), ('Furtada', 'Furtada'), ('Roubada', 'Roubada'), ('Perdida', 'Perdida'), ('Destruida', 'Destruída'), ('Inservivel', 'Inservível')], default='Disponivel', max_length=20)),
                ('obs', models.TextField(blank=True)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='cadastros.fornecedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BemIndividual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patrimonio', models.CharField(blank=True, max_length=100)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponível'), ('Em Uso', 'Em Uso'), ('Em Reparo', 'Em Reparo'), ('Recolhida', 'Recolhida'), ('Apreendida', 'Apreendida'), ('Furtada', 'Furtada'), ('Roubada', 'Roubada'), ('Perdida', 'Perdida'), ('Destruida', 'Destruída'), ('Inservivel', 'Inservível')], default='Disponivel', max_length=20)),
                ('tamanho', models.CharField(blank=True, max_length=50)),
                ('sexo', models.CharField(blank=True, max_length=20)),
                ('dt_val', models.DateField(blank=True, null=True)),
                ('obs', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bens', to='estoque.item')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('patrimonio_codigo', models.CharField(blank=True, max_length=100)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('calibre', models.CharField(blank=True, max_length=50)),
                ('comprimento_cano', models.CharField(blank=True, max_length=50)),
                ('quantidade_carregadores', models.IntegerField(blank=True, null=True)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='armas', to='estoque.item')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
