# Generated by Django 5.2.17 on 2026-08-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_arma_criado_por_bemindividual_criado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='estoque.compra'),
        ),
    ]
