# Generated by Django 5.2.17 on 2026-08-12 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('sigla', models.CharField(blank=True, max_length=20)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, max_length=30)),
                ('contato', models.CharField(blank=True, max_length=255)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('obs', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpcaoMenu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('grupo', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=255)),
                ('rotulo', models.CharField(max_length=255)),
                ('ordem', models.IntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['grupo', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Delegacia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('ativo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegacias', to='cadastros.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lotacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=255)),
                ('resp', models.CharField(blank=True, max_length=255)),
                ('area_atuacao', models.CharField(blank=True, max_length=255)),
                ('ais', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=255)),
                ('seccional', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotacoes', to='cadastros.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patrimonio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('delegacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonios', to='cadastros.delegacia')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patrimonios', to='cadastros.departamento')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Policial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(max_length=50)),
                ('cpf', models.CharField(blank=True, max_length=20)),
                ('nome', models.CharField(max_length=255)),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('tel', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('obs', models.TextField(blank=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policiais', to='cadastros.departamento')),
                ('lotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policiais', to='cadastros.lotacao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
