# Generated by Django 5.2.17 on 2026-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastros", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="responsavel",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
