# Generated by Django 5.2.17 on 2026-08-12 20:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0001_initial'),
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('policial_nome', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('data_rec', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('obs', models.TextField(blank=True)),
                ('armeiro', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cautela',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('data_saida', models.DateField(blank=True, null=True)),
                ('data_prev', models.DateField(blank=True, null=True)),
                ('data_dev', models.DateField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=50)),
                ('policial_nome', models.CharField(blank=True, max_length=255)),
                ('item_desc', models.CharField(blank=True, max_length=255)),
                ('qtd', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pendente de Assinatura', 'Pendente de Assinatura'), ('Ativa', 'Ativa'), ('Pendente (Devolução)', 'Pendente (Devolução)'), ('Devolvido', 'Devolvido')], default='Pendente de Assinatura', max_length=30)),
                ('condicao_dev', models.CharField(blank=True, choices=[('Disponivel', 'Disponível'), ('Em Uso', 'Em Uso'), ('Em Reparo', 'Em Reparo'), ('Recolhida', 'Recolhida'), ('Apreendida', 'Apreendida'), ('Furtada', 'Furtada'), ('Roubada', 'Roubada'), ('Perdida', 'Perdida'), ('Destruida', 'Destruída'), ('Inservivel', 'Inservível')], max_length=20, null=True)),
                ('motivo_recolhimento', models.CharField(blank=True, max_length=255)),
                ('nup', models.CharField(blank=True, max_length=100)),
                ('numero_io_bo', models.CharField(blank=True, max_length=100)),
                ('numero_serie_reparo', models.CharField(blank=True, max_length=100)),
                ('obs_dev', models.TextField(blank=True)),
                ('serie', models.CharField(blank=True, max_length=100)),
                ('assinatura_digital', models.TextField(blank=True)),
                ('assinatura_dev', models.TextField(blank=True)),
                ('token_confirmacao', models.CharField(blank=True, max_length=100)),
                ('token_confirmacao_dev', models.CharField(blank=True, max_length=100)),
                ('email_policial', models.EmailField(blank=True, max_length=254)),
                ('hash_assinatura', models.CharField(blank=True, max_length=100)),
                ('hash_assinatura_dev', models.CharField(blank=True, max_length=100)),
                ('id_confirmacao', models.CharField(blank=True, max_length=100)),
                ('hash_confirmacao', models.CharField(blank=True, max_length=100)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('qtd_carregadores', models.IntegerField(blank=True, null=True)),
                ('confirmado_via_email', models.BooleanField(default=False)),
                ('confirmado_via_email_dev', models.BooleanField(default=False)),
                ('data_assinatura', models.DateTimeField(blank=True, null=True)),
                ('data_assinatura_dev', models.DateTimeField(blank=True, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautelas', to='cadastros.departamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cautelas', to='estoque.item')),
                ('lotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautelas', to='cadastros.lotacao')),
                ('policial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cautelas', to='cadastros.policial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('Entrada', 'Entrada'), ('Cautela', 'Cautela'), ('Devolucao', 'Devolução'), ('Baixa', 'Baixa')], max_length=20)),
                ('quantidade', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('data', models.DateTimeField()),
                ('arma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='estoque.arma')),
                ('delegacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='cadastros.delegacia')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='cadastros.departamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos', to='estoque.item')),
                ('patrimonio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos', to='cadastros.patrimonio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
