# Generated by Django 5.2.17 on 2026-08-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operacoes', '0003_sequencianumeracao_servico_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='calibre',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servico',
            name='categoria',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servico',
            name='data_dev',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servico',
            name='modelo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='servico',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='servico',
            name='pecas_substituidas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='servico',
            name='trabalho_realizado',
            field=models.TextField(blank=True),
        ),
    ]
